config/routes.rb
Rails.application.routes.draw do

  namespace :control_panel do
    resources :users, except: [:show]
  end

  namespace :control_panel do
    get 'dashboard/index'
  end

  get 'order/index'

  get 'products/index'

  get 'customers/index'

  get 'homepage/info'

  devise_for :users
  root 'homepage#index'
  resources :categories, except: [:show]
  resources :tables, except: [:show]
  resources :customers, except: [:show]
  resources :products, except: [:show]
  resources :orders

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord

  # Associations
  has_one :product

  # Validates
  validates :name, presence: true, uniqueness: true, length: { maximum: 30, too_long: "-> %{count} characters is the maximum allowed", minimum: 2, too_short: "-> %{count} characters is the minimum allowed" }
  validates :description, presence: true, length: { maximum: 500, too_long: "-> %{count} characters is the maximum allowed", minimum: 10, too_short: "-> %{count} characters is the minimum allowed" }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    # @categories = Category.all.order(:name).page(params[:page])
    @q = Category.ransack(params[:q])
    @categories = @q.result.page(params[:page])
  end

  def new
    @category = Category.new()
  end

  def edit
  end

  def create
    @category = Category.create(params_category)

    unless @category.errors.any?
      redirect_to categories_path, notice: "Category #{@category.name} registered!!"
    else
      render :new
    end
  end

  def update
    if @category.update(params_category)
      redirect_to categories_path, notice: "Category updated!!"
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      redirect_to categories_path, notice: "#{@category.name} deleted!!"
    else
      render :index
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def params_category
    params.require(:category).permit(:name, :description)
  end
end

app/views/categories/_form.html.erb
<br>
<div class="row justify-content-center">
  <div class="col-sm-6">
    <div class="card card-body mb-2">
      <%= form_with(model: category, local: true) do |form| %>
        <% if category.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

            <ul>
            <% category.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <hr>
        <h4 class="lead text-center">Category</h4>
        <hr>

        <div class="panel panel-default">
          <div class="panel-body">
            <%= render 'shared/label_name', :form => form %>
            <%= form.text_field :name, id: :category_name, :class => "form-control", :placeholder => "Name" %><br>

            <%= render 'shared/label_description', :form => form %>
            <%= form.text_field :description, id: :category_description, :class => "form-control", :placeholder => "Description" %><br>

            <%= render 'shared/button', :form => form %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<hr>
  <form class="form-inline">
    <div class="form-group">
      <i class="fas fa-list-ul mb-2 mr-sm-2"></i>
      <h4 class="text-left mb-2 mr-sm-2">List of Categories</h4>
    </div>
    <div class="form-group">
      <%= link_to 'New Category', new_category_path, :class => "btn btn-md btn-success mb-2 mr-sm-2", :role => "button" %>
      <div class="input-group mb-2">
        <%= search_form_for @q do |f| %>
          <%= f.search_field :name_cont, class: "form-control", placeholder: "Search by Name" %>
          <div class="input-group-append">
            <%= f.submit 'Search', class: "btn btn-outline-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </form>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th class="text-md-center"><i class="fas fa-edit"></i></th>
      <th class="text-md-center"><i class="fas fa-trash-alt"></i></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Edit', edit_category_path(category), :class => "btn btn-md btn-info btn-block", :role => "button" %></td>
        <td><%= link_to 'Delete', category, :class => "btn btn-md btn-danger btn-block disabled", :role => "button", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br><%= paginate @categories %>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>