config/routes.rb
Rails.application.routes.draw do

  namespace :control_panel do
    resources :users, except: [:show]
  end

  namespace :control_panel do
    get 'dashboard/index'
  end

  get 'order/index'

  get 'products/index'

  get 'customers/index'

  get 'homepage/info'

  devise_for :users
  root 'homepage#index'
  resources :categories, except: [:show]
  resources :tables, except: [:show]
  resources :customers, except: [:show]
  resources :products, except: [:show]
  resources :orders

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  # Associations
  belongs_to :category

  # Validates
  validates :name, presence: true, uniqueness: true, length: { maximum: 30, too_long: "-> %{count} characters is the maximum allowed", minimum: 2, too_short: "-> %{count} characters is the minimum allowed" }
  validates :description, presence: true, length: { maximum: 500, too_long: "-> %{count} characters is the maximum allowed", minimum: 2, too_short: "-> %{count} characters is the minimum allowed" }
  validates :category, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :set_category, only: [:new, :edit, :update]

  def index
    # @products = Product.all.order(:name).page(params[:page])
    @q = Product.ransack(params[:q])
    @products = @q.result.page(params[:page]).includes(:category)
  end

  def new
    @product = Product.new()
  end

  def edit
  end

  def create
    @product = Product.create(params_product)

    unless @product.errors.any?
      redirect_to products_path, notice: "Product #{@product.name} registered!!"
    else
      render :new
    end
  end

  def update
    if @product.update(params_product)
      redirect_to products_path, notice: "Product updated!!"
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_path, notice: "#{@product.name} deleted!!"
    else
      render :index
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def set_category
    @categories = Category.all
  end

  def params_product
    params.require(:product).permit(:name, :price, :description, :category_id)
  end
end

app/views/products/_form.html.erb
<br>
<div class="row justify-content-center">
  <div class="col-sm-6">
    <div class="card card-body mb-2">
      <%= form_with(model: product, local: true) do |form| %>
        <% if product.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
            <% product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <hr>
        <h4 class="lead text-center">Product</h4>
        <hr>

        <div class="panel panel-default">
          <div class="panel-body">
            <%= render 'shared/label_name', :form => form %>
            <%= form.text_field :name, id: :product_name, :class => "form-control", :placeholder => "Name" %><br>

            <%= form.label :price, :class => "sr-only" %>
            <%= form.number_field :price, id: :product_price, step: :any, :class => "form-control", :placeholder => "Price" %><br>

            <%= render 'shared/label_description', :form => form %>
            <%= form.text_field :description, id: :product_description, :class => "form-control", :placeholder => "Description" %><br>

            <%= form.label :category, :class => "sr-only" %>
            <%= form.collection_select(:category_id, @categories, :id, :name, {prompt: "Select a category"}, {class: "form-control"}) %><br>

            <%= render 'shared/button', :form => form %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<hr>
  <form class="form-inline">
    <div class="form-group">
      <i class="fas fa-list-ul mb-2 mr-sm-2"></i>
      <h4 class="text-left mb-2 mr-sm-2">List of Products</h4>
    </div>
    <div class="form-group">
      <%= link_to 'New Product', new_product_path, :class => "btn btn-md btn-success mb-2 mr-sm-2", :role => "button" %>
      <div class="input-group mb-2">
        <%= search_form_for @q do |f| %>
          <%= f.search_field :name_cont, class: "form-control", placeholder: "Search by Name" %>
          <div class="input-group-append">
            <%= f.submit 'Search', class: "btn btn-outline-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </form>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th class="text-md-center"><i class="fas fa-edit"></i></th>
      <th class="text-md-center"><i class="fas fa-trash-alt"></i></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= product.category.name %></td>
        <td><%= link_to 'Edit', edit_product_path(product), :class => "btn btn-md btn-info btn-block", :role => "button" %></td>
        <td><%= link_to 'Delete', product, :class => "btn btn-md btn-danger btn-block disabled", :role => "button", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br><%= paginate @products %>

app/views/products/new.html.erb
<%= render 'form', product: @product %>