config/routes.rb
Rails.application.routes.draw do

  namespace :control_panel do
    resources :users, except: [:show]
  end

  namespace :control_panel do
    get 'dashboard/index'
  end

  get 'order/index'

  get 'products/index'

  get 'customers/index'

  get 'homepage/info'

  devise_for :users
  root 'homepage#index'
  resources :categories, except: [:show]
  resources :tables, except: [:show]
  resources :customers, except: [:show]
  resources :products, except: [:show]
  resources :orders

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Small Restaurant</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link" do %>
              <i class="fas fa-utensils"></i>
            <% end %>
          </li>
          <li class="nav-item"><%= link_to 'Orders', orders_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Tables', tables_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Categories', categories_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Products', products_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Customers', customers_path, class: "nav-link" %></li>

          <% unless user_signed_in? %>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link" do %>
                <i class="fas fa-sign-in-alt"></i>
                <i class="fas fa-user-tie"></i>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                <i class="fas fa-user-tie"></i>
                <i class="fas fa-sign-out-alt"></i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to '#', class: "nav-link" do %>
                <i class="fas fa-clock"></i>
                <span id="time">60:00</span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">

      <% if notice %>
        <div id="flash">
          <div class="alert alert-success">
            <%= flash[:notice] %>
          </div>
        </div>
      <script>
        setTimeout();
      </script>
      <% end -%>

      <%= yield %>

    </div>
    <script>
      function startTimer(duration, display) {
          var timer = duration, minutes, seconds;
          setInterval(function () {
              minutes = parseInt(timer / 60, 10)
              seconds = parseInt(timer % 60, 10);

              minutes = minutes < 10 ? "0" + minutes : minutes;
              seconds = seconds < 10 ? "0" + seconds : seconds;

              display.text(minutes + ":" + seconds);

              if (--timer < 0) {
                  timer = duration;
              }
          }, 1000);
      }

      jQuery(function ($) {
          var sixtyMinutes = 60 * 60,
              display = $('#time');
          startTimer(sixtyMinutes, display);
      });
    </script>
  </body>
</html>

app/views/layouts/control_panel.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Dashboard Template for Bootstrap</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'control_panel', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <%= link_to 'Small Restaurant', root_path, class: "navbar-brand col-sm-3 col-md-2 mr-0" %>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <% if notice %>
        <div id="flash">
          <div class="alert alert-success">
            <%= flash[:notice] %>
          </div>
        </div>
      <script>
        setTimeout();
      </script>
      <% end -%>

      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to control_panel_dashboard_index_path, class: "nav-link active" do %>
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                <% end %>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file"></span>
                  Orders
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  Category
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="users"></span>
                  Customers
                </a>
              </li>
              <li class="nav-item">
                <%= link_to control_panel_users_path, class: "nav-link" do %>
                  <span data-feather="user-check"></span>
                  Users
                <% end %>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Reports
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <%= yield %>
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
  </body>
</html>